### ISSUE TITLE
Add format file content

### ISSUE THREAD

**Issue by VovanR** [VovanR/bemstyla#22]
### TODO
- [x] Add format file content
- [x] Plug to index and creator
- [x] Plug to cli
- [x] Readme

### Default, `styl`, `sass`
```css
.foo
    {}
```
Usage
```styl
.foo
    border: none
```

### `css`, `less`, `scss`
```css
.foo {
}
```
Usage
```css
.foo {
    border: none;
}
```
